pipeline {
    agent any
    tools {
        maven 'maven'
    }
    stages {
        stage('Build') {
            steps {
                sh 'ls -la'
                sh 'cd example-service/'
                sh 'pwd'
                sh 'ls -la'
                sh 'mvn clean package'
            }
        }
    }
}