pipeline {
    agent any
    tools {
        maven 'maven'
    }
    stages {
        stage('Build') {
            steps {
                sh 'cd example-service/ & mvn -B -DskipTests clean package'
            }
        }
    }
}